stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: group-manager
  DOCKER_IMAGE: 172.16.98.151:5000/${APPLICATION_NAME}

containerization:
  stage: containerization
  script:
    - cp ${SECRETS} ./secrets.js
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}

deployment:
  stage: deployment
  script:
    - kubectl apply -f deployment.yml
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: staging
