apiVersion: v1
kind: Service
metadata:
  labels:
    run: ${APPLICATION_NAME}
  name: ${APPLICATION_NAME}
spec:
  ports:
  - port: 80
    nodePort: ${SERVICE_PORT}
  selector:
    app: ${APPLICATION_NAME}
  type: NodePort
